server:
  port: 8080

spring:
  application:
    name: client-service

  datasource:
    url: jdbc:postgresql://localhost:5431/client
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
